apiVersion: v1
kind: Service
metadata:
  name: javaspringcache01
spec:
  ports:
  - port: 11211
#    nodePort: 11201
    targetPort: javaspringmc-port
    protocol: TCP
  selector:
    app: javaspringmc 
  type: NodePort
