apiVersion: v1
kind: Pod
metadata:
  name: javaspringmc
  labels:
    app: javaspringmc
spec:
  containers:
  - name: javaspringmc
    image: memcached
    ports:
    - name: javaspringmc-port
      containerPort: 11211

