apiVersion: v1
kind: Pod
metadata:
  name: javaspringdb
  labels:
    app: javaspringdb
spec:
  containers:
  - name: javaspringdb
    image: myjddocker/javaspring-db:V1
    ports:
    - name: javaspringdb-port
      containerPort: 3306

    env:
     - name: MYSQL_ROOT_PASSWORD
       value: "javaspringdbpass"

