apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # actual password encoded with base64 command, storing encrypted password only
  db-pass: amF2YXNwcmluZ3Bhc3M=   
  rmq-pass: Z3Vlc3Q=
