apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaspringmc
  labels:
    app: javaspringmc
spec:
  selector:
    matchLabels:
      app: javaspringmc
  replicas: 1
  template:
    metadata:
      labels:
        app: javaspringmc
    spec:
      containers:
      - name: javaspringmc
        image: memcached
        ports:
        - name: jsmc-port
          containerPort: 11211
