apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaspringmq01
  labels:
    app: javaspringmq01
spec:
  selector:
    matchLabels:
      app: javaspringmq01
  replicas: 1
  template:
    metadata:
      labels:
        app: javaspringmq01
    spec:
      containers:
      - name: javaspringmq01
        image: rabbitmq       # use default official image from dockerhub, no need for custom
        ports:
        - name: javaspringmq01-port
          containerPort: 15672
        env: 
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:     # already defined in k8s secrets, take from there now.
             secretKeyRef:
               name: app-secret
               key: rmq-pass
         - name: RABBITMQ_DEFAULT_USER
           value: "guest"

