apiVersion: v1
kind: Service
metadata:
  name: javaspringmq01
spec:
  ports:
  - port: 5672
    targetPort: javaspringmq01-port
    protocol: TCP
  selector:
    app: javaspringmq01
  type: ClusterIP
