apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaspringdb
  labels:
    app: javaspringdb
spec:
  selector:
    matchLabels:
      app: javaspringdb
  replicas: 1
  template:
    metadata:
      labels:
        app: javaspringdb
    spec:
      containers:
      - name: javaspringdb
        image: myjddocker/javaspringdb:V1
        args:
          - "--ignore-db-dir=lost+found"
        volumeMounts: 
          - mountPath: /var/lib/mysql
            name: javaspringdb-data
        ports:
        - name: jsdb-port
          containerPort: 3306
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass
      nodeSelector:
        zone: eu-central-1a
      volumes:
        - name: javaspringdb-data
          awsElasticBlockStore:
            volumeID: "vol-069bea1986003d43e"
            fsType: ext4