apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaspringapp
  labels: 
    app: javaspringapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaspringapp
  template:
    metadata:
      labels:
        app: javaspringapp
    spec:
      containers:
      - name: javaspringapp
        image: javaspringapp:V1
        ports:
        - name: jsapp-port
          containerPort: 8080
      # has multiple containers, other deployments have just a single container.
      # (1) the java app container in image (2) the db init pod container, should be created first, 
      # to achieve this execute a shell script from busybox container. 
      initContainers:    # forces to run this container first
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup javaspringdb; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup javaspringcache01; do echo waiting for mydb; sleep 2; done;']
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-js-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: javaspringapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50        
