apiVersion: v1
kind: Service
metadata:
  name: javaspringapp-service
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: javaspringapp-port
    protocol: TCP
  selector:
    app: javaspringapp
  type: NodePort
