apiVersion: v1
kind: Pod
metadata:
  name: javaspringapp
  labels:
    app: javaspringapp
spec:
  containers:
  - name: javaspringapp
    image: myjddocker/javaspring-app:V1
    ports:
    - name: javaspringapp-port
      containerPort: 8080
