apiVersion: v1
kind: Service
metadata:
  name: javaspring-app-service
spec:
  ports:
  - port: 80
    targetPort: javaspring-app-port
    protocol: TCP
  selector:
    app: javaspring-app
  type: LoadBalancer
