apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaspring-app-deployment
  labels:
    app: javaspring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaspring-app
  template:
    metadata:
      labels:
        app: javaspring-app
    spec:
      containers:
      - name: javaspring-app
        image: myjddocker/javaspring-app:V1
        ports:
        - name: javaspring-app-port
          containerPort: 8080
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: javaspring-app-service
spec:
  ports:
  - port: 80
#    nodePort: 31001
    targetPort: javaspring-app-port
    protocol: TCP
  selector:
    app: javaspring-app
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-javaspring-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: javaspring-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
