version: "3"
services:
  javaspring-db:
    image: myjddocker/javaspringdb:V1
    ports:
      - "3306:3306"
    volumes:
      - javaspringdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=javaspringdbpass
  javaspringcache01:
    image: memcached
    ports:
      - "11211:11211"
  javaspringmq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  javaspringapp:
    image: myjddocker/javaspringapp:V1
    ports:
      - "8080:8080"
    volumes:
      - javaspringappdata:/usr/local/tomcat/webapps
  javaspringweb:
    image: myjddocker/javaspringweb:V1
    ports:
      - "80:80"
volumes:
  javaspringdbdata: {}
  javaspringappdata: {}
